### ISSUE TITLE
Goerli Testnet no longer works

### ISSUE THREAD

**Issue by razvandragomirescu** [commonprefix/kevlar#13]
When trying to run the latest version with "-n 5" (Goerli), on both Mac and Linux, I get this:

**root@139-144-74-59:~# kevlar -n 5**
Sync started using 2 Provers from period(466) to period(646)
failed GET request (https://light-optimistic-goerli-2.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180): Request failed with status code 503
failed GET request (https://light-optimistic-goerli-1.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180): Request failed with status code 503
failed GET request (https://light-optimistic-goerli-2.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180): Request failed with status code 503
failed GET request (https://light-optimistic-goerli-1.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180): Request failed with status code 503
failed GET request (https://light-optimistic-goerli-2.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180): Request failed with status code 503
failed GET request (https://light-optimistic-goerli-1.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180): Request failed with status code 503
failed GET request (https://light-optimistic-goerli-2.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180): Request failed with status code 503
failed to fetch committee hash for prover(1) at period(467) Error: GET request failed: https://light-optimistic-goerli-2.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180
    at handleGETRequest (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/utils.js:62:15)
    at handleGETRequest (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/utils.js:70:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LightOptimisticProver._getHashes (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/provers/light-optimistic/client.js:17:21)
    at async LightOptimisticProver.getCommitteeHash (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/provers/light-optimistic/client.js:23:26)
    at async file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/optimistic/index.js:97:28
    at async Promise.all (index 1)
    at async OptimisticLightClient.syncFromGenesis (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/optimistic/index.js:95:37)
    at async OptimisticLightClient.sync (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/base-client.js:24:33)
    at async ClientManager.sync (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/rpc-bundle/client-manager.js:33:9)
    at async main (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/rpc-bundle/start-rpc.js:52:26)
failed GET request (https://light-optimistic-goerli-1.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180): Request failed with status code 503
failed to fetch committee hash for prover(0) at period(467) Error: GET request failed: https://light-optimistic-goerli-1.herokuapp.com/sync-committee/hashes?startPeriod=467&maxCount=180
    at handleGETRequest (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/utils.js:62:15)
    at handleGETRequest (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/utils.js:70:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LightOptimisticProver._getHashes (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/provers/light-optimistic/client.js:17:21)
    at async LightOptimisticProver.getCommitteeHash (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/provers/light-optimistic/client.js:23:26)
    at async file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/optimistic/index.js:97:28
    at async Promise.all (index 0)
    at async OptimisticLightClient.syncFromGenesis (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/optimistic/index.js:95:37)
    at async OptimisticLightClient.sync (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/base-client.js:24:33)
    at async ClientManager.sync (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/rpc-bundle/client-manager.js:33:9)
    at async main (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/rpc-bundle/start-rpc.js:52:26)
Error: none of the provers responded honestly :(
    at OptimisticLightClient.syncFromGenesis (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/optimistic/index.js:159:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OptimisticLightClient.sync (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/base-client.js:24:33)
    at async ClientManager.sync (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/rpc-bundle/client-manager.js:33:9)
    at async main (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/rpc-bundle/start-rpc.js:52:26)

**root@139-144-74-59:~# kevlar -n 5 -c light**
Sync started using 1 Provers from period(466) to period(646)
Validating Prover(0)
failed to fetch sync update for period(466)
Error: no honest prover found
    at LightClient.syncFromGenesis (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/light/index.js:59:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LightClient.sync (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/clients/base-client.js:24:33)
    at async ClientManager.sync (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/rpc-bundle/client-manager.js:33:9)
    at async main (file:///usr/local/share/.config/yarn/global/node_modules/@lightclients/kevlar/dist/rpc-bundle/start-rpc.js:52:26)

Mainnet works for both client types:

**root@139-144-74-59:~# kevlar**
Sync started using 4 Provers from period(738) to period(744)
Optimistic update verified for slot 6099971
RPC Server started at http://localhost:8546

**root@139-144-74-59:~# kevlar -c light**
Sync started using 1 Provers from period(738) to period(744)
Validating Prover(0)
Optimistic update verified for slot 6099972
RPC Server started at http://localhost:8546

**Comment by rista404** [comment]
Goerli was replaced by Sepolia which Kevlar now supports.
